#配置应用名称-注册时使用
spring:
 application:
  name: spring-eureka-provider
  zipkin:
  　base-url: http://zipkin-server:9411
#配置服务注册发现地址
eureka:
 client:
   serviceUrl:
     defaultZone: http://127.0.0.1:8088/eureka/

server:
  port: 8089
